name: Deploy CICD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login Docker Hub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
      - name: Build the Docker image
        run: docker build -t victorbtdias159/cicd-deploy .
      - name: Push to Dockerhub
        run: docker push victorbtdias159/cicd-deploy:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Login Docker Hub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
      - name: Pull Docker image
        run: sudo docker pull victorbtdias159/cicd-deploy:latest
      - name: Delete Old docker container
        run: sudo docker rm -f api || true
      - name: Run Docker Container
        env:
          TZ: "America/Sao_Paulo"
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          ADMINJS_COOKIE_PASSWORD: ${{ secrets.ADMINJS_COOKIE_PASSWORD }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
        run: |
          sudo docker run -d --restart unless-stopped -p 3030:3030 --name api \
          -e TZ="${TZ}" \
          -e DATABASE_URL="${DATABASE_URL}" \
          -e POSTGRES_PASSWORD="${POSTGRES_PASSWORD}" \
          -e ADMINJS_COOKIE_PASSWORD="${ADMINJS_COOKIE_PASSWORD}" \
          -e USER_PASSWORD="${USER_PASSWORD}" \
          -e NODE_ENV="${NODE_ENV}" \
          victorbtdias159/cicd-deploy:latest
      - name: Clean up unused Docker images
        run: sudo docker system prune -f
