name: Deploy CICD API

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build the Docker image
        run: docker build -t victorbtdias159/cicd-deploy .
      - name: Push to Dockerhub
        run: docker push victorbtdias159/cicd-deploy:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Docker image
        run: sudo docker pull victorbtdias159/cicd-deploy:latest
      - name: Delete Old docker container
        run: sudo docker rm -f api || true
      - name: Run Docker Container
        run: sudo docker run -d -p 3030:3030 --name api victorbtdias159/cicd-deploy
      - name: Clean up unused Docker images
        run: sudo docker system prune -f
